{{- if .Values.service.boot}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-frontend
  labels:
    app: url-shortener-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-frontend
  template:
    metadata:
      labels:
        app: url-shortener-frontend
    spec:
      containers:
        - name: url-shortener-frontend
          image: michel/url-shortener-frontend:LOCAL-SNAPSHOT
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-frontend
spec:
  selector:
    app: url-shortener-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
{{- end}}